# Generated by Django 2.1.3 on 2018-11-11 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
                name='Users',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('firebase_token', models.CharField(max_length=128)),
                    ('keywords', models.CharField(max_length=512, null=True)),
                    ('created_at', models.DateTimeField(auto_now_add=True)),
                    ('updated_at', models.DateTimeField(auto_now=True)),
                ],
                options={
                    'db_table': 'subscribers',
                },
        ),
        migrations.AddField(
                model_name='sources',
                name='created_at',
                field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
                preserve_default=False,
        ),
        migrations.AddField(
                model_name='sources',
                name='updated_at',
                field=models.DateTimeField(auto_now=True),
        ),
    ]
