# Generated by Django 2.1.3 on 2018-11-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
                model_name='news',
                name='country',
                field=models.CharField(blank=True, max_length=2),
        ),
    ]
