# Generated by Django 2.1.3 on 2018-11-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0002_news_country'),
    ]

    operations = [
        migrations.RemoveField(
                model_name='news',
                name='id',
        ),
        migrations.AlterField(
                model_name='news',
                name='title',
                field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
