# Generated by Django 2.1.3 on 2018-11-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0002_auto_20181111_0646'),
    ]

    operations = [
        migrations.RenameModel(
                old_name='Sources',
                new_name='Source',
        ),
        migrations.RenameModel(
                old_name='Users',
                new_name='Subscriber',
        ),
        migrations.AlterField(
                model_name='news',
                name='content',
                field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
                model_name='news',
                name='description',
                field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
                model_name='news',
                name='url',
                field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
                model_name='news',
                name='urlToImage',
                field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
