# Generated by Django 2.1.3 on 2018-11-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0003_auto_20181112_0501'),
    ]

    operations = [
        migrations.AlterField(
                model_name='subscriber',
                name='firebase_token',
                field=models.CharField(max_length=128, unique=True),
        ),
    ]
